### ISSUE TITLE
part5 scss 

### ISSUE THREAD

**Issue by Hjname** [wooritech/wooricamp-whj#15]
해당 부분 학습내용 정리링크 입니다.

https://github.com/wooritech/wooricamp-whj/tree/main/Part5%20SCSS

- scss란 무엇인가
- scss에서 사용하는 문법 (주석, 중첩, 상위 선택자 참조 등)
- scss 변수 선언 방식
- `@mixin`을 사용한 재활용
- 반복문 `@for`과 `@each`
- scss 함수
- 데이터의 종류

**Comment by Malloc72P** [comment]
깃헙에서 글을 쓸 때 골뱅이를 붙이게 되면, 해당 텍스트를 아이디로 쓰는 사람을 멘션하게 됩니다.
@Hjname 이런식으로요
![image](https://github.com/wooritech/wooricamp-whj/assets/41663269/1f8d59e1-4753-4c67-8822-caea3122e3a4)

이 경우 해당 유저에게 알림 메일이 전송될 수 있으니 주의해주세요

멘션하려는게 아닌 경우, 백틱으로 꼭 감싸주세요. `@Hjname`이렇게요

**Comment by Malloc72P** [comment]
sass에 대해 학습하셨네요

저도 sass에 대해 잘 몰라서 간단하게 공부하고 느낀점을 남겨봐요

### Sass 변수

- CSS에도 변수가 있는데, sass의 변수는 뭐가 특이할까 하고 찾아봤는데 좀 더 향상된 기능을 제공하네요
- 예를들면, CSS의 변수는 속성의 값으로만 사용이 가능한데, Sass는 선택자나 속성명 등, 더 다양한 곳에서 사용할 수 있어요  
- 미디어쿼리같은걸 사용할 때, 화면 너비를 상수로 뽑아서 재사용하고 싶었는데, Sass를 사용하면 이게 가능하겠네요

### 중첩 구조

- CSS를 쓰다보면 선택자가 엄청 길어지는데, 대부분의 경우 HTML요소가 중첩되어서 이렇게 된다고 생각해요
- 하지만 CSS는 중첩구조를 지원하지 않아서 같은 내용의 선택자가 중복되곤 했었어요
- 그런데 Sass는 중첩구조를 지원해서 이러한 고민을 해결할 수 있어서 정말 좋은 것 같네요

### 그 외에도...

- 가끔 CSS 스타일을 작성하다보면, 배경색이라던가,  박스쉐도우, 테두리 등의 속성이 여러 클래스에서 중복되어 나타나곤 했어요
- 이럴때 믹스인 기능을 사용해서, 중복되는 CSS 코드를 해결하면 좋을 것 같네요.
- 그 밖에도 다양한 유틸함수나 반복문 등이 있는점도 좋았던 것 같아요
