### ISSUE TITLE
Part6 css 프레임워크 부트스트랩 

### ISSUE THREAD

**Issue by Hjname** [wooritech/wooricamp-whj#16]
# 부트스트랩 5. 0. 2 버전기준 학습

## 부트스트랩 홈페이지의 Docs에 위치한 컴포너트 기능 코드 사용법 학습

- 모달, 툴팁, 버튼

## 부트스트랩 홈페이지의 Docs에 위치한 커스텀마이징 기능 코드 사용법 학습

- 색상, 트리쉐이킹(최적화)

**Comment by Malloc72P** [comment]
🚀
