### ISSUE TITLE
Part7 중 파슬 번들러 내용 정리

### ISSUE THREAD

**Issue by Hjname** [wooritech/wooricamp-whj#17]
# 정리한 내용 

"https://github.com/wooritech/wooricamp-whj/tree/bundler"

- 번들러의 개요
- 정적 파일 연결, autoprefixer,babel,CLI 학습

**Comment by onlydel** [comment]
열심이네요. 👍

**Comment by Malloc72P** [comment]
자바스크립트 번들러는 이제는 필수가 된 기술이라고 볼 수 있지요

단순히 여러 파일을 하나의 파일로 묶어주는건 물론, 최적화를 해서 번들된 모듈의 크기를 최소화해주거나,
개발자를 위한 다양한 편의기능(ex: 개발서버구성)을 제공하거나,
자바스크립트의 최신 기능을 이전 브라우저에서도 돌릴 수 있게 해주는 등의 다양한 기능을 제공합니다.

캐로셀도 마찬가지로 번들러 환경에서 만들고, 단일 모듈로 빌드해서 배포할 수 있습니다
나중에 여유가 생기면 같이 해보면 좋을 것 같네요 🔥
