### ISSUE TITLE
타입스크립트 (TypeScript) 내용 정리본 요약과 링크

### ISSUE THREAD

**Issue by Hjname** [wooritech/wooricamp-whj#21]
### 타입 스크립트란 무엇인가?

- js에 타입을 부여하는 확장어

### 타입 스크립트의 타입들

https://www.notion.so/Type-0a1ef3c39d7f407091c55d565622001a

### 타입 단언이란?

- 프로그래머가 너보다 내가 잘아니까 그냥 내 말 들어라고 선언하는것

### 타입의 이름을 지어하는 방법

1. 타입 별칭
2. 인터페이스

### 시그니처

1. 호출 시그니처
2. 인덱스 시그니처

### 함수 오버로딩

매개변수가 다른 함수 두개 합치기

### 제어접근자

- public
- protected
- -private

### 제네릭

데이터 타입의 일반화

### Utility 타입

- partial
- pick
- omit
- exclude
- required
- record<,>
- return Type<T>

### 정리 링크

https://www.notion.so/TypeScript-208cc8c399cf419bbe8adcfe2c683b07

**Comment by Hjname** [comment]
타입 스크립트 정리 추가

**Comment by Malloc72P** [comment]
시간이 너무 지나서 확인하게 되었네요 ㅎㅎ
노션 링크가 권한때문에 열람할 수 없네요. 다른 사람이랑 공유하려면, 따로 공유 링크 만들어야해요.

제네릭스는 진짜 많이 사용되니까 잘 정리해두면 좋을 것 같아요.
우리가 흔히 사용하는 array.map도 제네릭스를 사용한답니다
![image](https://github.com/user-attachments/assets/2e6d94a4-877a-43f0-811f-6a8dda96da2d)
```ts
/**
 * Calls a defined callback function on each element of an array, and returns an array that contains the results.
 * @param callbackfn A function that accepts up to three arguments. The map method calls the callbackfn function one time for each element in the array.
 * @param thisArg An object to which the this keyword can refer in the callbackfn function. If thisArg is omitted, undefined is used as the this value.
 */
map<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): U[];
```
이런 식으로, map 함수의 선언을 확인해보면 제네릭스가 사용되는 것을 확인할 수 있어요.
이렇게 하면 함수 내부에서 사용할 타입을 외부에서 지정해서 사용할 수 있습니다.
함수가 좀 더 다양한 타입을 처리할 수 있는 장점이 생기구요.

또, 유틸리티 타입도 많이 사용합니다.
이러한 타입도 vscode에서 `go to definition`을 해보면, 아래와 같이 나오는데요,

```ts
/**
 * Construct a type with a set of properties K of type T
 */
type Record<K extends keyof any, T> = {
    [P in K]: T;
};
```
인덱스 시그니쳐를 사용해서 구현한 것을 알 수 있습니다.
인덱스 시그니쳐를 처음 봤을 때 이걸 대체 어디에서 사용하지? 라고 궁금해할 수 있을 것 같은데, 이런 식으로 활용된다고 알면 좋을 것 같네요.

정리 고생했습니다.
